#server:
#  port: 8081
#spring:
#  application:
#    name: springcloud-provide-dept
#  datasource:
#    url: jdbc:mysql://localhost:3306/db01?serverTimezone=Asia/Shanghai&amp&useSSL=true&amp&useUnicode=true&amp&characterEncoding=utf-8
#    username: root
#    password: root
#    driver-class-name: org.gjt.mm.mysql.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#mybatis:
#  type-aliases-package: com.tuzhi.springcloud.pojo
#  mapper-locations: classpath:mybatis/mapper/*.xml